
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
development:
  <<: *default
  database: Suv_development
test:
  <<: *default
  database: Suv_test

production:
  <<: *default
  database: Suv_production
  